name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CIBW_BUILD: "${{ matrix.cibw.build || '*' }}"
      CIBW_SKIP: "${{ matrix.cibw.skip || '' }}"
      CIBW_ARCHS_LINUX: "${{ matrix.cibw.arch || 'auto' }}"
      CIBW_ARCHS_MACOS: "${{ matrix.cibw.arch || 'auto' }}"
      CIBW_MANYLINUX_X86_64_IMAGE: "${{ matrix.cibw.manylinux_x86_64_image || '' }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            name: mac-cpython
            cibw:
              build: "cp36-*"

          - os: macos-11
            name: mac-pypy
            cibw:
              build: "pp37-*"

          - os: macos-11
            name: mac-arm
            cibw:
              arch: universal2
              build: "cp36-*"

          - os: ubuntu-20.04
            name: manylinux-x86_64
            cibw:
              arch: x86_64
              build: "cp36-manylinux*"

          - os: ubuntu-20.04
            name: manylinux-i686
            cibw:
              arch: i686
              build: "cp36-manylinux*"

          # additional manylinux variants, not specified in pyproject.toml:
          # build with newer 2_28 for cpython >= 3.10, pypy 3.9
          - name: manylinux-x86_64-2_28
            os: ubuntu-20.04
            cibw:
              arch: x86_64
              build: "cp310-manylinux* pp39-manylinux*"
              manylinux_x86_64_image: manylinux_2_28

          - os: ubuntu-20.04
            name: musllinux
            cibw:
              build: "cp36-musllinux*"

          - os: windows-2019
            name: win32
            architecture: x86
            cibw:
              build: "cp36-win32"

          - os: windows-2019
            name: win-pypy
            architecture: x64
            cibw:
              build: "pp36-win_amd64"

          - os: windows-2019
            name: win_amd64
            architecture: x64
            cibw:
              build: "cp36-win_amd64"
     
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: ${{ matrix.architecture }}


      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: cd cling && python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./cling/wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: cd cling && pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: ./cling/dist/*.tar.gz
