name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.cibw.build }}
    runs-on: ${{ matrix.os }}

    env:
      CIBW_BUILD: "${{ matrix.cibw.build || '*' }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            name: mac-cpython
            architecture: x86_64
            cibw:
              build: "cp39-macosx_x86_64"

          - os: macos-11
            name: mac-cpython-arm
            architecture: arm64
            cibw:
              build: "cp39-macosx_arm64"

          - os: macos-11
            name: mac-pypy
            architecture: x86_64
            cibw:
              build: "pp39-macosx_x86_64"

          - os: macos-11
            name: mac-pypy-arm
            architecture: arm64
            cibw:
              build: "pp39-macosx_arm64"

          - os: ubuntu-20.04
            name: manylinux-x86_64
            architecture: x86_64
            cibw:
              build: "cp39-manylinux_x86_64"

          - os: ubuntu-20.04
            name: manylinux-arch64
            architecture: arch64
            cibw:
              build: "cp39-manylinux_aarch64"

          - os: ubuntu-20.04
            name: manylinux-pypy-arch64
            architecture: arch64
            cibw:
              build: "pp39-manylinux_aarch64"

          - os: ubuntu-20.04
            name: manylinux-i686
            architecture: i686
            cibw:
              build: "cp39-manylinux_i686"

          - os: ubuntu-20.04
            name: manylinux-pypy-x86_64
            architecture: x86_64
            cibw:
              build: "pp39-manylinux_x86_64"

          - os: ubuntu-20.04
            name: musllinux-x86_64
            architecture: x86_64
            cibw:
              build: "cp39-musllinux_x86_64"

          - os: ubuntu-20.04
            name: musllinux-pypy-x86_64
            architecture: x86_64
            cibw:
              build: "pp39-musllinux_x86_64"

          - os: ubuntu-20.04
            name: musllinux-i686
            architecture: i686
            cibw:
              build: "cp39-musllinux_i686"

          - os: windows-2019-x86
            name: win32
            architecture: x86
            cibw:
              build: "cp39-win32"

          - os: windows-2019-amd64
            name: win_amd64
            architecture: AMD64
            cibw:
              build: "cp39-win_amd64"

          - os: windows-2019-arm64
            name: win32-arm64
            architecture: ARM64
            cibw:
              build: "cp39-win_arm64"

     
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: ${{ matrix.architecture }}


      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: cd cling && python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./cling/wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: cd cling && pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: ./cling/dist/*.tar.gz
